<?php formbuilder_admin_nav('extensions'); ?>
<fieldset class="options metabox-holder">

<style type="text/css">
.fbbtn {
	-moz-box-shadow:inset 0px 1px 0px 0px #d9fbbe;
	-webkit-box-shadow:inset 0px 1px 0px 0px #d9fbbe;
	box-shadow:inset 0px 1px 0px 0px #d9fbbe;
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #b8e356), color-stop(1, #a5cc52) );
	background:-moz-linear-gradient( center top, #b8e356 5%, #a5cc52 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#b8e356', endColorstr='#a5cc52');
	background-color:#b8e356;
	-webkit-border-top-left-radius:0px;
	-moz-border-radius-topleft:0px;
	border-top-left-radius:0px;
	-webkit-border-top-right-radius:0px;
	-moz-border-radius-topright:0px;
	border-top-right-radius:0px;
	-webkit-border-bottom-right-radius:0px;
	-moz-border-radius-bottomright:0px;
	border-bottom-right-radius:0px;
	-webkit-border-bottom-left-radius:0px;
	-moz-border-radius-bottomleft:0px;
	border-bottom-left-radius:0px;
	text-indent:0;
	border:1px solid #83c41a;
	display:inline-block;
	color:#ffffff;
	font-family:Arial;
	font-size:15px;
	font-weight:bold;
	font-style:normal;
	height:65px;
	line-height:65px;
	width:131px;
	text-decoration:none;
	text-align:center;
	text-shadow:1px 1px 0px #86ae47;
	display: block;
	float: left;
	margin-right: 20px;
}
.fbbtn:hover {
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #a5cc52), color-stop(1, #b8e356) );
	background:-moz-linear-gradient( center top, #a5cc52 5%, #b8e356 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#a5cc52', endColorstr='#b8e356');
	background-color:#a5cc52;
	color: #444;
}
.fbbtn:active {
	position:relative;
	top:1px;
}
.fb-ext {
	min-height: 132px;
}
.fb-ext p {
	font-size: 20px;
}
</style>
	
	<div>

		<div class="postbox fb-ext">
			<h3 class='info-box-title hndle'><?php _e('FormBuilder SMTP Controls', 'formbuilder'); ?> </h3>
			<div class="inside">
				<p class='clear'>
					<a class="fbbtn" href="http://www.warkensoft.com/wordpress/formbuilder/formbuilder-smtp/">Get Extension</a>
					<?php _e('The FormBuilder SMTP Controls extension allows FormBuilder send it’s email through any standard SMTP service such as Mandrill or SendGrid.', 'formbuilder'); ?>
					<a href="http://www.warkensoft.com/wordpress/formbuilder/formbuilder-smtp/"><?php _e('Read more...', 'formbuilder'); ?></a>
				</p>
			</div>
		</div>
		
		<div class="fb-ext" style="text-align: center;">
			<p>More to come...</p>
		</div>
	
	</div>
	
	<div class='clear' />

</fieldset>
